# version: '3.8'

services:
  mycache:
    image: go-cache:latest
    container_name: cache
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    ports:
      - "9000:8080"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=go_cache
    networks:
      - my-cache-network      
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql        
    networks:
      - my-cache-network

volumes:
  db:
    driver: local

networks:
  my-cache-network: